import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { STATIC_PAGE_ROUTES } from '@/config/public-routes.js';

/**
 * Guards the committed sitemap. It is regenerated by `scripts/generate-sitemap.js`
 * during prebuild, so these assertions describe what that script must keep true.
 */

const sitemapPath = resolve(__dirname, '..', 'public-vite', 'sitemap.xml');
const xml = readFileSync(sitemapPath, 'utf8');

type Entry = { loc: string; lastmod: string | null };

const entries: Entry[] = xml
  .split('<url>')
  .slice(1)
  .map((block) => ({
    loc: block.match(/<loc>([^<]+)<\/loc>/)?.[1] ?? '',
    lastmod: block.match(/<lastmod>([^<]+)<\/lastmod>/)?.[1] ?? null,
  }));

describe('sitemap.xml', () => {
  it('lists every public static route', () => {
    const locs = new Set(entries.map((entry) => entry.loc));
    for (const route of STATIC_PAGE_ROUTES) {
      expect(locs, `sitemap is missing ${route.path}`).toContain(`https://mcc-cal.com${route.path}`);
    }
  });

  it('omits changefreq and priority', () => {
    // Google has stated for years that it ignores both. Emitting them is noise that
    // also invites treating them as a substitute for an accurate lastmod.
    expect(xml).not.toContain('<changefreq>');
    expect(xml).not.toContain('<priority>');
  });

  it('formats every lastmod as an ISO date', () => {
    for (const { loc, lastmod } of entries) {
      if (lastmod === null) continue;
      expect(lastmod, `${loc} has a malformed lastmod`).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });

  it('never dates a page in the future', () => {
    // A future lastmod is the fastest way to get the signal distrusted entirely.
    const today = new Date().toISOString().slice(0, 10);
    for (const { loc, lastmod } of entries) {
      if (lastmod === null) continue;
      expect(lastmod <= today, `${loc} claims a lastmod in the future: ${lastmod}`).toBe(true);
    }
  });

  it('dates the portfolio routes, which change most often', () => {
    // These read their lastmod from the generated manifests, so they should always
    // resolve regardless of git history depth.
    const portfolioRoutes = ['/journalism', '/nature', '/portraits', '/events', '/concerts'];
    for (const path of portfolioRoutes) {
      const entry = entries.find((candidate) => candidate.loc === `https://mcc-cal.com${path}`);
      expect(entry, `sitemap is missing ${path}`).toBeDefined();
      expect(entry?.lastmod, `${path} should take its lastmod from its manifest`).not.toBeNull();
    }
  });

  it('does not report every page as changed on the same day', () => {
    // The failure mode of deriving dates from a shallow clone: every file resolves to
    // the boundary commit, so the whole site claims to have changed at once.
    const dated = entries.map((entry) => entry.lastmod).filter(Boolean);
    if (dated.length < 4) return;
    expect(new Set(dated).size, 'every lastmod is identical, which suggests a bad date source').toBeGreaterThan(1);
  });

  it('has no duplicate URLs', () => {
    const locs = entries.map((entry) => entry.loc);
    expect(locs.length).toBe(new Set(locs).size);
  });
});
