name: Build manifests

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
      - 'scripts/gen-manifest.js'
      - '.github/workflows/build-manifest.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # --- DIAGNOSTICS (helps if something goes wrong) ---
      - name: Show working tree & confirm script exists
        run: |
          pwd
          ls -la
          ls -la scripts || true
          test -f scripts/gen-manifest.js && echo "✅ scripts/gen-manifest.js found" || (echo "❌ Missing scripts/gen-manifest.js" && exit 1)
          test -d "images/Portfolios/Concert/The Book Club/The Book Club" && echo "✅ Target image dir exists" || (echo "❌ Target image dir missing" && exit 1)

      # --- GENERATE MANIFEST ---
      - name: Generate manifest (Book Club)
        run: |
          node scripts/gen-manifest.js "images/Portfolios/Concert/The Book Club/The Book Club"

      # --- COMMIT IF CHANGED ---
      - name: Commit & push manifest
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            git commit -m "Auto-update manifest.json"
            git push
          else
            echo "No changes to commit."
          fi
