name: Build manifests

on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
      - 'scripts/gen-manifest.js'
      - '.github/workflows/build-manifest.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Optional: quick sanity info in logs
      - name: Show repo tree (top level)
        run: |
          pwd
          ls -la
          test -f scripts/gen-manifest.js && echo "✅ scripts/gen-manifest.js found" || (echo "❌ Missing scripts/gen-manifest.js" && exit 1)

      # Generate manifests for EVERY images/* subdirectory containing image files
      - name: Generate manifests for all image directories
        shell: bash
        run: |
          set -euo pipefail
          changed=0
          while IFS= read -r -d '' dir; do
            # Does this dir contain any jpg/jpeg/png/webp (case-insensitive)?
            if compgen -G "$dir/*.[jJ][pP][gG]" > /dev/null || \
               compgen -G "$dir/*.[jJ][pP][eE][gG]" > /dev/null || \
               compgen -G "$dir/*.[pP][nN][gG]" > /dev/null || \
               compgen -G "$dir/*.[wW][eE][bB][pP]" > /dev/null; then
              echo "↻ Generating manifest for: $dir"
              node scripts/gen-manifest.js "$dir"
              changed=1
            fi
          done < <(find images -type d -print0)

          if [[ $changed -eq 0 ]]; then
            echo "No image directories found (or no changes)."
          fi

      - name: Commit & push manifests
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            git commit -m "Auto-update manifests"
            git push
          else
            echo "No changes to commit."
          fi
