name: Build manifests
on:
  push:
    branches: [ main ]
    paths:
      - 'images/**'
      - 'scripts/gen-manifest.js'
      - '.github/workflows/build-manifest.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate manifest (Book Club)
        run: node scripts/gen-manifest.js "images/Portfolios/Concert/The Book Club/The Book Club"

      - name: Commit & push manifest
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            git commit -m "Auto-update manifest.json"
            git push
          fi
